
===  Service Group - *RAS_AGENT* (servicegroup_id: 0x0000B)
A RAS agent works as a bridge between the RISCV RERI compliant errors source and
the ACPI CPER tables. One of its role is to convert RERI records into ACPI CPER records.

Each error source in a system has a unique 32-bit identification number called as `ERR_SRC_ID`.
RAS agent provides services to enumerate various error sources and get their descriptors.

Below table lists the services in this group:
[#table_ras_agent_services]
.RAS Agent Services
[cols="1, 3, 2", width=100%, align="center", options="header"]
|===
| Service ID	| Service Name 			| Request Type
| 0x01		| GET_NUM_ERR_SRCS		| NORMAL_REQUEST
| 0x02		| GET_ERR_SRCS_ID_LIST		| NORMAL_REQUEST
| 0x03		| GET_ERR_SRC_DESC		| NORMAL_REQUEST
|===

==== Service: *GET_NUM_ERR_SRCS*
This service is used to query number of error sources available in the system.

[#table_ras_agent_getnum_err_srcs_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| START_INDEX	| uint32	| Starting index of `ERR_SRC_ID` list. + 
`0` for the first call, subsequent calls will use the next index of the remaining 
items.
|===

[#table_ras_agent_getnum_err_srcs_response_data]
.Response Data
[cols="1, 2, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="2,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and number of error sources
returned as NUM_ERR_SRCS.
!===
- Other errors <<table_error_codes>>
| 1	|	NUM_ERR_SRCS 	| uint32 	| Number of Error Sources
|===

==== Service: *GET_ERR_SRCS_ID_LIST*
This service returns a list of `ERR_SRC_ID` for all error soruces present in the system.
The `ERR_SRC_ID` can be used to get the associated descriptor of the error source.

[#table_ras_agent_get_err_srcs_id_list_request_data]
.Request Data
[cols="1, 3, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| START_INDEX	| uint32	| Starting index of `ERR_SRC_ID` list. + 
`0` for the first call, subsequent calls will use the next index of the remaining 
items.
|===

[#table_ras_agent_get_err_srcs_id_list_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="7,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and list of error sources returned
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| _Reserved_ and must be `0`.
| 2	| REMAINING	| uint32	| Remaining number of error source IDs
| 3	| RETURNED	| uint32	| Number of error source IDs returned so far.
| 4	| ERR_SRC_ID[0]	| uint32	| Error source ID array where each entry in the
array is a unique error source ID.

N is number of error source returned by the `GET_NUM_ERR_SRCS` message response. +
| 5	| ERR_SRC_ID[1]	| uint32	|
| ...	| ERR_SRC_ID[N-1]	| uint32	|
|===

==== Service: *GET_ERR_SRC_DESC*
This service returns the error source descriptor of an error source specified by `ERR_SRC_ID`.
The format of the error source descriptor is defined in ACPI specification v6.4 Section 18.3.2.8 (GHESv2).

The RAS agent populates the error source descriptor fields according to the error source specified by `ERR_SRC_ID`.

NOTE: The error source descriptor has an `error_status_structure` field which is a generic address
structure (`GAS`) as defined in ACPI v6.4 Section 5.2.3.2. This field specifies the location of a
register that contains the physical address of a block of memory that holds the error status data for
the specified error source. This block of memory is referred to as `error_status_block`. The allocation of
`error_status_block` is platform dependent and is done by the RAS agent. The physical address of `error_status_block`
is stored in the `error_status_structure` field of the error source descriptor being returned.

[#table_ras_agent_get_err_src_desc_request_data]
[cols="1, 2, 1, 7", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| ERR_SRC_ID	| uint32	| Error source ID for which attributes are to be returned
| 1	| BYTE_OFFSET	| uint32	| Offset from which the descriptor is to be read +
	Offset `0` for the first call, subsequent byte offset of the remaining bytes.
|===

[#table_ras_agent_get_err_src_desc_response_data]
.Response Data
[cols="1, 3, 1, 7a", width=100%, align="center", options="header"]
|===
| Word	| Name 		| Type		| Description
| 0	| STATUS	| int32		| Return Status Code
[cols="7,5"]
!===
! *Error Code* 	!  *Description*
! RPMI_SUCCESS	! Service completed successfully and partial/complete error source descriptor returned.
!===
- Other errors <<table_error_codes>>
| 1	| FLAGS		| uint32	| _Reserved_ and must be `0`.
| 2	| REMAINING	| uint32	| Remaining number of bytes to be read
| 3	| RETURNED	| uint32	| Number of bytes read so far
| 4	| ERR_SRC_DESC[N]	| uint8	| Full or partial descriptor +
	N is number of bytes free till the end of the message buffer.
|===
